package pl.pabilo8.modworks.annotations.item;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Used to annotate an enum with item
 * @author Pabilo8
 * @since 11.08.2023
 */
@Retention(RetentionPolicy.SOURCE)
@Target({ElementType.TYPE})
public @interface GeneratedItemModels
{
	/**
	 * @return item name
	 */
	String itemName();

	/**
	 * @return item texture path
	 */
	String texturePath() default "";

	/**
	 * @return base model type of all entries
	 */
	ItemModelType type() default ItemModelType.ITEM_SIMPLE;

	/**
	 * @return enum to be used for reference instead of the class using this annotation
	 */
	Class<? extends Enum> valueSet() default Enum.class;

	/**
	 * @return whether models should only be generated by entries annotated with {@link GeneratedSubItemModel}
	 */
	boolean onlyInAnnotated() default false;
}
