name: Build Project

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Create a Dev Build
    env:
      GITHUB_USERNAME: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.OPTIMIZATION_TOKEN }}
      JAVA_VERSION: 8
      SIGN_KEYSTORE: ~/keystore.jks
      SIGN_ALIAS: ${{secrets.SIGN_ALIAS}}
      SIGN_STOREPASS: ${{secrets.SIGN_STOREPASS}}
      SIGN_KEYPASS: ${{secrets.SIGN_STOREPASS}}
      SIGN_TIMESTAMP: ${{secrets.SIGN_TIMESTAMP}}
      iiMavenReleasesUsername: ${{secrets.IIMAVENRELEASESUSERNAME}}
      iiMavenReleasesPassword: ${{secrets.IIMAVENRELEASESPASSWORD}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 8

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: '~/keystore.jks'
          encodedString: ${{ secrets.SIGN_KEYSTORE }}

      - name: Execute Gradle publish
        run: chmod +x gradlew ; ./gradlew publish --scan