name: Test Results

on:
  push:
    branches:
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'corretto'
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Build and Upload Package
      run: chmod +x gradlew ; ./gradlew test

    - name: Test Report
      uses: phoenix-actions/test-reporting@v8
      id: test-report               # Set ID reference for step
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Tests            # Name of the check run which will be created
        path: test/results/**/TEST-*.xml    # Path to test results
        reporter: java-junit        # Format of test results